name: 'Monorepo Setup'
description: 'Setup Node, pnpm, install dependencies, and restore turbo cache.'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install
      shell: bash

    - name: Build
      run: pnpm build

inputs:
  node-version:
    description: 'Node.js version'
    required: true
