name: Setup
description: 'Setup Node, pnpm, install dependencies, and build.'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install
      shell: bash
      
inputs:
  node-version:
    description: 'Node.js version'
    required: true
