packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma
  - unrs-resolver
