-- CreateTable
CREATE TABLE "Board" (
    "Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Slug" TEXT NOT NULL,
    "Description" TEXT,
    "OwnerId" INTEGER NOT NULL,
    "CreatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Board_OwnerId_fkey" FOREIGN KEY ("OwnerId") REFERENCES "User" ("UserId") ON DELETE RESTRICT ON UPDATE CASCADE
);
