name: CI

on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main
      - 'v*'

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      node-version: '20'

  build-and-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: ./.github/workflows/setup.yml
        with:
          node-version: '20'

      - name: Run Tests
        if: ${{ inputs.run-tests }}
        run: pnpm test

      - name: Build
        run: pnpm build
