name: CI

on:
  pull_request:
    branches:
      - main
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Monorepo Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          node-version: '20'

      # - name: Run Tests
      #   if: ${{ github.event_name == 'workflow_call' && inputs.run-tests == true || github.event_name == 'pull_request' }}
      #   run: pnpm test

      - name: Lint
        run: pnpm lint
