name: CI

on:
  workflow_call:
    inputs:
      run-tests:
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Monorepo Setup
        uses: ./.github/actions/monorepo-setup
        with:
          node-version: '20'

      - name: Run Tests
        if: github.event_name == 'workflow_call' && inputs.run-tests == true
        run: pnpm test

      - name: Lint
        run: pnpm lint
