name: Release

on:
  workflow_call:
    inputs:
      create-tag:
        required: false
        type: boolean
        default: true
    secrets:
      GITHUB_TOKEN:
        required: true
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      node-version: '20'
      fetch-depth: 0

  version-and-tag:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and pnpm
        uses: ./.github/workflows/setup.yml
        with:
          node-version: '20'
          fetch-depth: 0

      - name: Build
        run: pnpm build

      - name: Version and Create PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: release version'
          title: 'Release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        if: ${{ inputs.create-tag && steps.changesets.outputs.hasChangesets == 'true' }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag v$VERSION
          git push origin v$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
