name: Release

on:
  workflow_call:
    inputs:
      create-tag:
        required: false
        type: boolean
        default: true
    secrets:
      GITHUB_TOKEN:
        required: true
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Monorepo Setup
        id: monorepo-setup
        uses: ./.github/actions/monorepo-setup
        with:
          node-version: '20'

      - name: Version and Create PR
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: 'chore: release version'
          title: 'Release version'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        if: >
          ${{
            (github.event_name == 'workflow_call' && inputs.create-tag == true) ||
            (github.event_name == 'push')
          }} && steps.changesets.outputs.hasChangesets == 'true'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag v$VERSION
          git push origin v$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
